- name: Create production server
  hosts: localhost
  connection: local
  vars:
    terraform_rc_path: .terraformrc
    terraform_path: ./terraform-openstack
  tasks:
    - name: Prepare TF (set yandex mirror)
      copy:
        src: "{{ terraform_rc_path }}"
        dest: ~/.terraformrc

    - name: Run terraform
      environment:
        TF_VAR_user_name: "{{ lookup('env', 'TF_VAR_user_name') }}"
        TF_VAR_password: "{{ lookup('env', 'TF_VAR_password') }}"
      terraform:
        project_path: "{{ terraform_path }}"
        force_init: yes
        state: present
      register: trfrm

    - name: Export server IP up
      lineinfile:
        path: ~/server_ip
        regexp: '^SERVER_IP='
        line: "SERVER_IP={{ trfrm.outputs.servers.value.serverip }}"
        mode: '0644'
        create: yes

    - name: Add instance host
      add_host:
        name: tpb-server
        groups: nodes
        ansible_user: ubuntu
        ansible_host: "{{ trfrm.outputs.servers.value.serverip }}"
        ansible_ssh_private_key_file: ~/.ssh/orlov
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"


    
- name: Wait for instance creating
  hosts: localhost
  connection: local

  tasks:
    - name: Wait for a ssh port become available
      wait_for:
        host: "{{ trfrm.outputs.servers.value.serverip }}"
        port: 22

- name: Start production database
  hosts: tpb-server
  become: yes
  tasks:
    - name: Download MongoDB 7.0 GPG Key (ASCII)
      get_url:
        url: https://pgp.mongodb.com/server-7.0.asc
        dest: /etc/apt/keyrings/mongodb-server-7.0.asc
        mode: '0644'

    - name: Convert GPG key to binary format
      command: >
        gpg --dearmor -o /etc/apt/keyrings/mongodb-server-7.0.gpg /etc/apt/keyrings/mongodb-server-7.0.asc
      args:
        creates: /etc/apt/keyrings/mongodb-server-7.0.gpg

    - name: Add MongoDB apt repository
      copy:
        dest: /etc/apt/sources.list.d/mongodb-org-7.0.list
        content: |
          deb [signed-by=/etc/apt/keyrings/mongodb-server-7.0.gpg] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse

    - name: Update apt and install MongoDB
      apt:
        update_cache: yes
        name: mongodb-org
        state: present

    - name: Start and enable MongoDB service
      service:
        name: mongod
        state: started
        enabled: yes

- name: Prepare production for deploy
  hosts: tpb-server
  vars:
    service_path: moviebot.service
    terraform_path: ./terraform-openstack
  tasks:
    - block:
      - name: Install JDK
        apt:
          update_cache: yes
          name: openjdk-21-jdk-headless
          state: present
        become: yes

      - name: Create bot app service
        copy:
          src: "{{ service_path }}"
          dest: /etc/systemd/system/moviebot.service
          mode: '0777'
        become: yes

      - name: Reload services
        systemd:
          daemon_reload: true
          name: moviebot
          state: stopped
        become: yes

      rescue:
       - name: Clean up resources in case of error
         terraform:
           project_path: "{{ terraform_path }}"
           state: absent
           targets: openstack_compute_instance_v2.orlov_server
         delegate_to: localhost
