# lab5.yaml
# Ansible playbook для развертывания moviebot

- name: Provision OpenStack VM and record IP
  hosts: localhost
  connection: local
  vars:
    terraform_path: "./terraform-openstack"   # 👉 Путь к папке с .tf-файлами
  tasks:
    - name: Run Terraform apply
      environment:
        TF_VAR_user_name: "{{ lookup('env','TF_VAR_user_name') }}"
        TF_VAR_password:  "{{ lookup('env','TF_VAR_password') }}"
      terraform:
        project_path: "{{ terraform_path }}"
        force_init: yes
        state: present
      register: tf

    - name: Save SERVER_IP to file
      copy:
        dest: ~/SERVER_IP
        content: "SERVER_IP={{ tf.outputs.server_ip.value }}"
        mode: '0644'

    - name: Add host to inventory
      add_host:
        name: moviebot
        groups: nodes
        ansible_host: "{{ tf.outputs.server_ip.value }}"
        ansible_user: ubuntu
        ansible_ssh_private_key_file: "~/.ssh/authorized_keys"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

- name: Wait for SSH
  hosts: localhost
  connection: local
  tasks:
    - name: Wait for SSH to become available
      wait_for:
        host: "{{ hostvars['localhost']['tf'].outputs.server_ip.value }}"
        port: 22
        timeout: 300

- name: Configure moviebot server
  hosts: nodes
  become: yes
  vars:
    repo_url: "https://github.com/gasmed/movie-recommendation-bot.git"
    app_dir: "/home/ubuntu/moviebot"
    jar_name: "moviebot.jar"
    service_file: "moviebot.service"
  tasks:
    - name: Install prerequisites
      apt:
        update_cache: yes
        name:
          - gnupg
          - curl
          - git
          - maven
          - openjdk-21-jdk-headless
        state: present

    - name: Add MongoDB repo key
      ansible.builtin.shell: |
        curl -fsSL https://pgp.mongodb.com/server-7.0.asc \
          | gpg --dearmor -o /usr/share/keyrings/mongodb-server-7.0.gpg
      args:
        creates: /usr/share/keyrings/mongodb-server-7.0.gpg

    - name: Add MongoDB apt repo
      ansible.builtin.apt_repository:
        filename: "mongodb-org-7.0"
        repo: "deb [signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse"
        state: present

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present
        update_cache: yes

    - name: Start and enable MongoDB
      service:
        name: mongod
        state: started
        enabled: yes

    - name: Clone moviebot repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: main

    - name: Build JAR with Maven
      shell: mvn clean package -DskipTests
      args:
        chdir: "{{ app_dir }}"

    - name: Copy JAR to home
      copy:
        src: "{{ app_dir }}/target/{{ jar_name }}"
        dest: "/home/ubuntu/{{ jar_name }}"
        owner: ubuntu
        mode: '0755'

    - name: Deploy systemd service
      copy:
        src: "{{ service_file }}"
        dest: /etc/systemd/system/{{ service_file }}
        mode: '0644'

    - name: Reload and start moviebot
      systemd:
        daemon_reload: true
        name: moviebot
        state: started
        enabled: true
